### ISSUE TITLE
What markup language will we support?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#10]
What sort of formatting do we want to support, and how do we envision users interacting with it?

For the latter, we basically seem to have three choices: a WYSIWYG editor, typing markup directly, or both. Thoughts?

**Comment by Kaelas17** [comment]
I don't know what this would be called or what the back-end would look like but I can toss out some features I like and hate:

Likes- 
Buttons. Basically, I don't want to have to type out commands to alter the text. Having to stop in the middle of a creative flow to recall how to use strikethrough or change color or whatnot can really break a train of thought and ruin what would have been a good post.

Active review: whether it's having an echoed box that shows the final product or simply having the text box I type in showing the final product, I want to be able to see what will be shown when I hit post without having to having anything load. Or having to go back and edit it ten times to get it right.

Options: as I referenced in my buttons like, I would love having more than just bold, italics, underlined and big/medium/small fonts.  Strikethrough, super- and sub-script are all great. Colors (even just the basic twelve pack of crayons colors) are great. Emoticons are fun too but I'd prefer to be able use manual ones as default and being able to use a button to input fancy ones.

Hates-
Too helpful autoformatting: if I want to indent something, I can do it myself, thanks. Don't try and predict what I want indented, you're always wrong, MC Word. Thank you, die in a fire. And don't even get me started on columns.

Autoplay: not sure if this falls under this topic but I figured I'd mention it. Not a fan of having embedded audio or video files playing without my telling them to directly. 

Hidden character limits: Not much worse than hitting enter on a post and getting a 'too many characters' error that won't even allow you to save the post. And hitting back doesn't save it either so all you can do is cry. 


That's about all I can think of atm.

**Comment by AccaliaDeElementia** [comment]
as a "power user" i sometimes find WYSIWYG editors annoying, especially if they aren't exactly WYSIWYG i would lean towards picking a decent WYSIWYG editor and add a per user option so the user if they prefer can tell the editor to get bent.

**Comment by yamikuronue** [comment]
Red suggested in another communication channel:

>About "a WYSIWYG editor, typing markup directly, or both", I mean... some things (i.e. phpbb or mediawiki) do halfway between in terms of a markup only textbox, but buttons for applying some tags, in the same style as buttons that would be in a WYSIWYG editor

**Comment by RaceProUK** [comment]
Red's suggestion also allows us to employ the concept of 'wizards'. For instance, a number of boards throw up a pop-up when you insert a link, so you can supply both the URL and the link text without worrying about syntax. And given we may have some complex BBCode extensions or similar, it'd make for an easy way to construct the magic incantation :wink:

**Comment by Onyx47** [comment]
I'd support "wizards" and generating markup: clicking a link button generates markup and places the cursor at proper position or provides additional dialogues where appropriate (links/images).

We'd also have to decide whether buttons generate both closing and opening tags or act as a toggle.

Another idea, if we go with something like markdown or mediawiki markup, we could add a intellisense-style help. Using markdown as an example, typing a `*` character on it's own line could pop up a tooltip with content similar to this:

```
* list item
*italic text*
**bold text**
```

**Comment by AccaliaDeElementia** [comment]
Right now i'm leaning towards either doing HTML or BBCode for the markup language.

which one we use would depend on the WYSIWYG editor we choose.

I'm leaning a bit towards HTML because that means the only processing step we need to take is an HTML sanitization pass to remove things like `<script>` tags and the dreaded `class="fa-spin"` (also to make sure all tags are closed.

Node already has some decent libraries for that sort of thing, and i looked at the BBCode parsing libraries available for Node when i was looking into using them to parse out bbcode style quotes from SockBot2.0.... they were all.... kinda crap.

**Comment by yamikuronue** [comment]
I  have put CKeditor into my mockup and plan to usability test it; that gives us HTML as a markup language (though it can export markdown instead) and a source-edit for those advanced users who want to fine-tune their posts
