### ISSUE TITLE
Do we want gamification features?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#11]
Do we want to have likes, badges, and what not?

**Comment by yamikuronue** [comment]
Personally, I feel this could be an entire update on its own: the Gamification update. I want to focus on having a solid core product first. But I'm open to other viewpoints :)

**Comment by AccaliaDeElementia** [comment]
gamification, not for version 1.0 i think, but for 2.0 maybe.

we should definitely get a wishlist of things to gamify.

**Comment by Cloak15** [comment]
Hmm...The badges are pretty cool. Do we want awardable badges or something that would be automatic?

**Comment by Cloak15** [comment]
Damn I did not mean to do that

**Comment by AccaliaDeElementia** [comment]
@Cloak15  if we do badges at all we will want manual grant/revoke at the minimum. and possibly some system for automatic grant/revoke.

I'm not concerned with having either feature right out of the gate as they are not dealbreakers, but we are designing this forum software for gamers so they will love, use, and abuse whatever gamification systems we give them (and that's kind of awesome)

**Comment by Cloak15** [comment]
Ah...though I'm also wondering if there could be a 'level' system. Something a bit like trust levels, but with more than 4? That one's a little harder to do, I admit but having something in place to encorage interaction with people using the system is always good.

**Comment by RaceProUK** [comment]
I'd say trust levels are more of a security feature than gamification, since the system you're referencing controls users' ability to perform moderator-type actions.

**Comment by Cloak15** [comment]
Hmm...Good point. And it would be less fun to have customization things behind 'levels' so you have to post or converse long enough to get things

**Comment by AccaliaDeElementia** [comment]
agreed that this is something we want to implement in future,

we should defer that sort of thing until we have a working forum though.

;-)
