### ISSUE TITLE
Do we want to allow child boards?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#13]
Aka, boards with a parent board? Games with a parent Game? Both? Neither?

**Comment by AccaliaDeElementia** [comment]
as games are boards with extra bits in i would say yes we should have support for this, at least in the DB level, we might not expose it in version 1.0 though.

**Comment by yamikuronue** [comment]
From the discussion in #17 I think we're leaning toward "Allowed". @AccaliaDeElementia also had suggested "mandatory", like, forcing boards into a tree hierarchy. Do we like that or is it overkill?

**Comment by RaceProUK** [comment]
Allowing boards to have child boards will give us a tree automatically; the question is do we allow multiple root boards or not?

**Comment by Cloak15** [comment]
Why would a game have a parent Game? Wouldn't that be handled by having multiple scenes going on at a time? I guess if a Game is a spin-off of another game, that would make it easy to find the source material.

**Comment by RaceProUK** [comment]
That's something we can handle in the UI/middle layer; in fact, we'll have to, as it can't be enforced in the DB (not without a potentially high performance penalty)

**Comment by AccaliaDeElementia** [comment]
I'm thinking that Allowed is the way we want to go with games being inside boards. They can be top level entities or children of a board.

That would imply that boards can be children of boards, but i'm not sure we want to support that for the alpha.

**Comment by yamikuronue** [comment]
Clarification point: We allow more than 2 levels,  yes? :)

**Comment by RaceProUK** [comment]
As far as the DB design is concerned, there's no difference between 2, 20, or 2,000 levels :wink:

**Comment by AccaliaDeElementia** [comment]
Unlimited levels, yes. but we reserve right to say :wtf: very loudly after you go more than three levels deep.

:-P

**Comment by AccaliaDeElementia** [comment]
I believe we're in agreement on this one for now. Closing ticket.

if further clarification is needed please reopen for further discussion
