### ISSUE TITLE
How are we handling OOC?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#17]
Okay, I think I've got a handle on the various options we've been discussing. For context, a Game contains Scenes, and a Board contains Threads.

**Option 1**: We have OOC posts intermingled with the IC posts inside a Scene, but marked specially so you can collapse them or skim past them. I'm not sure anyone's actually advocating this anymore, though.

**Option 2:** A Board, which is OOC, contains one or more Games, which are IC. The OOC chatter remains at the Board level, next to the Games. 

**Option 3**: A Game, which is IC, may contain one or more Boards, which are OOC. The OOC chatter goes in the child Board for the Game

**Option 4**: A Game, which is IC, may contain one or more Threads, which are OOC, as well as one or more Scenes, which are IC. The OOC threads live next to the IC scenes inside the Game

**Option 5**: A Board, which is a generic entity, contains one or more Scenes, which are IC, alongside the Threads, which are OOC. I'm not sure anyone has ever suggested this, but for completeness sake, it's here.

**Option 6**: A Game, which is IC, is optionally linked to a Board, which is OOC. The OOC chatter goes into the Board, and the IC scenes go into the Game, and never the twain shall meet. 

There are probably more options, as well.

**Comment by AccaliaDeElementia** [comment]
Options 4&5 seem to be the closest to what we're going for now.

A game lives inside a board, a game contains OOC chatter which may comprise multiple threads, and IC play which may be a semi connected directed graph of scenes (conceptually, not necessarily actually)

the difference between a board and a game in 4 and 5 is pretty vague, but i think it comes down to a game has at least one GM and thus may contain scenes and a board has no GM and thus may only contain OOC threads

**Comment by yamikuronue** [comment]
Why does a game have to live inside a board? Why aren't games top-level entities? 

Current state: When I join a forum, I want to know what games are open immediately, but often I'm presented with a list of generic boards: "Fantasy RPs" "Literate RPs" "Advanced RPs". I then have to drill down into a board, pick my way through the list of threads manually tagged "OOC" or "CLOSED" in order to curate for myself a list of games that are "[OPEN]" or "[ACCEPTING APPS]", and then click into every one to find out if I'm interested.

So to me, a list of games would be super helpful, and I don't want to go digging through boards to find them.

I do agree that OOC can live alongside IC though. As written in the reqdoc I was picturing 6, but I am coming around to 4

**Comment by RaceProUK** [comment]
We can solve the game/generic board issue with a single flag field; boards that have it set are games. Obviously, games would have more than just a flag, but that's the essence.

**Comment by AccaliaDeElementia** [comment]
My thinking on the boards containing games was for organization of completed/abandoned games.

and active game can and probably should be a top level entity, but a completed or abandoned one might be filed away to leave the front page less cluttered.

**Comment by yamikuronue** [comment]
We can do anything we want, we're coding wizards :) I'm more concerned with the mental model here: how do we want our users to perceive games and boards and where they put their IC text vs where they put their OOC text?

**Comment by yamikuronue** [comment]
@AccaliaDeElementia that's a good point. I think in the reqdoc we had started talking about the idea of archiving a game or board, when it's done with, to prevent new replies. So to me, that helps solve the issue of completed vs abandoned: rather than make admins move games around between folder-like boards, we let the UI be smart enough to de-emphasize closed games and emphasize open ones

**Comment by AccaliaDeElementia** [comment]
that was my idea, yeah. 

I'm not sure if i'd want to forbid an open game from being a member of a board, some admins may want it that way... still need to think on if i want to support active games inside boards.

**Comment by Kaelas17** [comment]
Grouping all threads related to a given game, whether IC or OC seems more organized in my head but being able to having a shopping list that gets down to the meat of the games is also attractive.

So...

Is there a reason why we couldn't, essentially, do both? Organize the main page with having IC and OC stuff in the same board but create a seperate 'looking for games' page that just lists the various games (organized by... filters? Finished, ongoing, fantasy, mature, free-form, dice, sci-fi, etc).

**Comment by RaceProUK** [comment]
In theory, we can make the UI show whatever we want, however we want :smile:

**Comment by yamikuronue** [comment]
@Kaelas17: They're basically separate issues. So we definitely can design a system where both IC and OOC live inside a Game, but also, where a Game doesn't have to live underneath a Board, but can be its own top-level entity. 

And yes, we're also UI wizards who can make magic in the GUI :)

**Comment by yamikuronue** [comment]
Talked to Kaelas offline and I realized something else: I think part of this boils down to Tags vs Categories. It sounds like @AccaliaDeElementia  is picturing a Category system, with Boards standing in for categories, like PhPBB does today. I'm picturing more of a Tag-based system where Games can be sorted, filtered, whatnot, however the UI makes sense, but they're not shoved into single boxes to live there forever.

**Comment by Kaelas17** [comment]
As long as things can be found, both work well enough but the tags and filter idea does have the benefit of being more flexible. Downside is that it can make finding something more difficult (repeating exact searches if the filtering is complex enough).

Another, albeit temporary, downside to cats is that when the forum first kicks off, it'll look really bare if there's only one thread for each category or so.

**Comment by Cloak15** [comment]
I'm definitely in favor of having OOC and IC separate and easy to see. This makes things rather easy to keep track of in the long run as I've had some issues in the long past with people using info for one in the other. As far as how their divided, do you think there would be more than one OOC room per game? If not, having the Game be an entity with OOC and IC threads within sounds like the easiest thing. It would even allow for a general OOC thread for the board with places to ask questions about specific games and even store the character lists for each game.

Well, one thing I was thinking is that we could have a flag for active, inactive, and completed. It makes it easy to see where the 'action is' so to speak.

**Comment by yamikuronue** [comment]
I don't know about OOC, but I think we settled on more than one IC thread (Scene) per game.

**Comment by RaceProUK** [comment]
And we can keep IC threads sorted above OOC threads easily enough. Or use a tabbed interface; an IC tab and an OOC tab. Either way, it's doable without having to artificially limit the number of each type of thread :smile:

**Comment by Kaelas17** [comment]
@RaceProUK Oh, have a vote for the idea of having tabs for IC and OC threads.

**Comment by Cloak15** [comment]
I would think you'd have the OOC thread first, if only so people could quickly see where to ask questions...also, tabs? I thought we were talking about tags

**Comment by yamikuronue** [comment]
Yeah actually, if we do a design with [IC] [OOC] [Integrated] as tabs, that pretty much suits everyone, right? and if we have a Game be a special case of board, we can do optional nesting as the answer to #13 (no required parent, but allowed), and I think that suits everyone?

**Comment by RaceProUK** [comment]
The tags for 'active', 'inactive', and 'completed' would be separate from the IC/OOC flag (or however we mark them).

Am I right in thinking [Integrated] would be IC and OOC combined?

**Comment by Kaelas17** [comment]
Tags, tabs and, err, tais. Shut up. Tags for threads to group them but tabs to split OC and IC threads makes sense to me. 

Basically, I'm all for giving as much in the way of options for customizing each user's interface as possible (up to the point of inducing code-rage and programing strokes for the Wizards of Sock).

**Comment by yamikuronue** [comment]
@RaceProUK  Yes ,that was the intent. Wording is obviously subject to change. Also this can be tabs, or it can be filter buttons like JIRA uses on their Kanban Boards, or whatnot. We'll do some design mockups and do some usability testing on them later in the process.

I'm going to go ahead and write up the filtering by IC vs OOC now. Might not be First Alpha milestone, but at least we can capture it.

The issue of whether we allow or force nesting goes in #13 so.... is there anything else to discuss here? Or are we happy?

**Comment by Cloak15** [comment]
I'm pretty good with that, at least till I see how all this would look like. I don't think I've seen a forum with filter tabs before, so it should be interesting.

**Comment by RaceProUK** [comment]
As far as I'm aware, no forum software has been designed for RPs before :wink:
