### ISSUE TITLE
Trial several ORM solution

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockRPG#20]
Trial several ORM solutions with our proposed DB design.

We want to test [Sequelize](https://www.npmjs.com/package/sequelize), [ORM](https://www.npmjs.com/package/orm) and [Objection](https://www.npmjs.com/package/objection) to see how well these ORM solutions meet our development needs and how performant they are on limited hardware.

We should have tests using postgres and sqlite as these are the two Databases we want to support initially (at minimum)

Tests should greate at least 5k boards/games and at least 10k threads/scenes (total) within the created boards. Tests should create at least 1m posts in threads/scenes, including at least one thread that has over 100k posts.

Tests should benchmark creation speeds as well as query speeds in both tested Database Engines

**Comment by RaceProUK** [comment]
To avoid polluting the main repo with a load of test code, I'll do the ORM profiling here:
https://github.com/RaceProUK/SockRPG-ORM-Testing

**Comment by RaceProUK** [comment]
From Slack:

raceprouk [20:32]
so, to sum up so far:
node-orm: defining models isn't as simple as it could be, and it doesn't take advantage of DB features
objection: the entire model has to be defined ​_twice_​: once to create the tables, again to create the objects that map to them; also has really ugly endless callchains
sequelize: defining the model is a cinch, and the syntax is nice and clean

…

accalia [20:34] 
`sequelize` wins


Code samples
Sequelize: https://github.com/RaceProUK/SockRPG-ORM-Testing/blob/master/sequelize/model.js
Objection: https://github.com/RaceProUK/SockRPG-ORM-Testing/blob/master/objection/model.js
Node-ORM: https://github.com/RaceProUK/SockRPG-ORM-Testing/blob/master/orm/model.js

So, with two votes for Sequelize, what does everyone else think?

**Comment by yamikuronue** [comment]
Agreed. Sequelize it is!

**Comment by AccaliaDeElementia** [comment]
Sequelize it is!

so mot it be
