### ISSUE TITLE
What sort of permissions system do we need?

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockRPG#21]
A more general question that will also cover #12

For instance, do we just define a set of flags, or have a more involved roles system? Or something else entirely? Or maybe even a mix of systems, depending on the permission being controlled?

**Comment by AccaliaDeElementia** [comment]
i would say a hierearchical structure would be involved. You get permissions at the Game/Board level (plus one master level) and if we allow nested boards you inherit the permissions from above in a well defined manner.

I think that you cannot get permissions at the thread/scene level, other than the one that says you cannot post as a character that is not in scene (unless using an NPC that the GM created and gave you, or an adhoc one that you as GM created)

other thoughts/ideas?

**Comment by RaceProUK** [comment]
The way I see it, most of the permissions boil down to a somewhat simplified version of the Unix system; we'd have Owner R/W (user) and World R/W (admin) as a minimum. That can be enforced with a simple flag, but anything finer-grained will need more careful design.

Similarly, there may be some areas where access needs to be whitelisted, so we may need the concept of an ACL too.

**Comment by yamikuronue** [comment]
I think at this point we have the level of detail we need to begin work, and we'll be revising the permissions system as we complete more features. Agreed?

**Comment by AccaliaDeElementia** [comment]
@yamikuronue: Agreed.
