### ISSUE TITLE
Read tracking

### ISSUE THREAD

**Issue by RaceProUK** [SockDrawer/SockRPG#26]
How detailed do we want to be? Track just the last read per user per thread (classic), or track per post (modern)? Or something else?

**Comment by yamikuronue** [comment]
We definitely want to keep track of where the user left off in an RP thread, because that's super useful, but we could do it to the level of when they last posted instead if we wanted.

**Comment by RaceProUK** [comment]
Since-last-posted would work well for RP threads, assuming people split RPs into scenes properly; unless you have an insane number of characters and players, I can't see more than a dozen posts between plays. However, it may not work so well for OOC threads and threads outside games; after all, some people may just read those, or post only after several hundred other posts have been made.

**Comment by Kaelas17** [comment]
So we're looking at... having the ability to pick your preference between 'read last' or 'read last read' post, possibly based on the tags the thread has (with perhaps the ability to manually opt in or out for specific threads). 

That level of flexibility is all sorts of awesome in my book and it sounds similar to what we're looking at in regards to email alerts, at least from a user point of view.

**Comment by AccaliaDeElementia** [comment]
hmm... we should track last read, jumping you back to the last post you read when returning, but have "auto-bookmarks" for the last post of each of your characters in the topic/scene allowing you to jump back there regardless of where you were reading before.

the auto bookmarks don't need to be tracked separately as that's data extractable from the DB easily, which means the only thing we need to actively track is last read position.

**Comment by RaceProUK** [comment]
I have a data model in mind already :smile:

**Comment by AccaliaDeElementia** [comment]
somehow i thought you would have.

:-D
