### ISSUE TITLE
Programming style: CPS vs. Promises

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockRPG#31]
Should we idiomatically use CPS or Promises for our async code?

That is do we want our API to be:

CPS
```
getUser(userID, (err,user) => {
    if (err) {
        return render_404(url, err);
    }
    return stringify(user);
});
```

or Promise
```
getUser(userId).
    then(user => {
        stringify(user);
    }).
    catch(err => {
        render_404(url, err);
    });
```

**Comment by RaceProUK** [comment]
I'd favour a Promise-based API, but I'm good either way

**Comment by yamikuronue** [comment]
The top code sample is much more readable. But I think that's formatting.

**Comment by AccaliaDeElementia** [comment]
point about the formatting...

Is this better?
```
getUser(userId).
then(user => {
    stringify(user);
}).
catch(err => {
    render_404(url, err);
});
```

**Comment by RaceProUK** [comment]
I know this is a tiny tweak, but I think starting lines with periods makes it clearer it's a method chain:
```
getUser(userId)
.then(user => {
    stringify(user);
})
.catch(err => {
    render_404(url, err);
});
```

**Comment by AccaliaDeElementia** [comment]
hmm.... that is true @RaceProUK  but will ASI catch us there or is that safe to do?

/me is paranoid about ASI breaking things

**Comment by Onyx47** [comment]
If you keep an open bracket on the previous line it should, logically, not kick in, should it?

**Comment by RaceProUK** [comment]
Er… dunno.

Maybe this?
```
getUser(userId).then(user => {
    stringify(user);
}).catch(err => {
    render_404(url, err);
});
```
The Sequelize samples use that style.

**Comment by Onyx47** [comment]
I like the above personally. That's what I use currently when working with jQuery.

**Comment by AccaliaDeElementia** [comment]
hmm.... yes but i think we're getting sidetracked on brace style which is a separate issue to discuss. ;-)

the real question here is CPS vs Promise.

:-D

**Comment by AccaliaDeElementia** [comment]
Okay, so as i understand it i have two votes for Promises (myself and @RaceProUK), one for CPS (@yamikuronue) and the rest abstaining.

Is that correct? Would Onyx like to place a vote? Would Yami possibly like to weigh in on Promises now that alternate (clearer) formatted examples have been presented?

**Comment by yamikuronue** [comment]
I would, but not right now.

**Comment by AccaliaDeElementia** [comment]
Fair enough then. I'll leave the ticket open for now.

**Comment by yamikuronue** [comment]
OKAY SO.

Promises are easier to read because I'm not used to the eS6 stuff. That said, I've had trouble with promises in the past being unintuitive when you start using libraries that implement promises sliiightly differently.

**Comment by AccaliaDeElementia** [comment]
A good point on the promise libraries having subtle differences, I think that's somewhat moderated by the quality of the built in promise in NodeJS, it seems that with move to 0.12 and beyone most promise based APIs user the global Promise object which means that they will at least have consistent behavior.

**Comment by yamikuronue** [comment]
I think we're all agreed on Promises then?

**Comment by RaceProUK** [comment]
Looks that way

**Comment by AccaliaDeElementia** [comment]
Yep. Looks like promises won the day.
