### ISSUE TITLE
Formal Code Style Guide

### ISSUE THREAD

**Issue by AccaliaDeElementia** [SockDrawer/SockRPG#32]
We need a formal code style guide to ensure consistent code throughout the project.

our current set of ESLint rules is a good step but not sufficient.

**Comment by RaceProUK** [comment]
Things like function/variable naming, argument ordering, identifier casing, that sort of stuff? Since ESLint already covers stuff like brace style and function length.

**Comment by AccaliaDeElementia** [comment]
basically exactly that sort of stuff, also code organization.

The earlier we get a clear set of guidelines the better we'll do sticking to them.

**Comment by yamikuronue** [comment]
Let's get the basics down and we can add to it as we go :)

**Comment by RaceProUK** [comment]
There's a few basics I think we can agree on quickly; admittedly some of these are already enforced by our ESLint config.
* All identifiers in camelCase, and no more than 20 characters
* Callbacks (where used) are always the last argument to a function
* Always use braces with control flow statements
* Opening brace on same line as statement
* Line length below 120 characters
* All functions and objects to be fully documented by JSDoc comments, regardless of visibility

IIRC, we stuck to all these rules for SockBot 2.0, and that turned out pretty well; see no reason not to do the same here :smile:

**Comment by AccaliaDeElementia** [comment]
added an update to one of your rules but otherwise seems like a good start. I'll knock together a fll document for revioew later this week.

**Comment by RaceProUK** [comment]
I was working under the assumption that any rule could be broken within reason, if it helps code clarity :wink:

**Comment by AccaliaDeElementia** [comment]
ah. fair enough then. :-D

**Comment by RaceProUK** [comment]
@Onyx47 reminded me: I'm used to PascalCase for class names; is that a style we want to adopt?

**Comment by AccaliaDeElementia** [comment]
Given that i'm tempted to avoid inheritance as much as possible for much of the code i don't think it's that big a deal.

The reasoning behind avoiding inheritance is that it's so rartely necessary in webcoding that many people aren't familliar with it and i'd like to keep as low a barrier to understanding as possible.

/me must admit that the vagaries of prototypical inhertence makes her skull ache.

**Comment by RaceProUK** [comment]
I was thinking of using PascalCase more to differentiate instantiable classes from inline JSON objects; see PostBuffer in SockBot 2.0

**Comment by yamikuronue** [comment]
I agree with that, I've seen that often enough. Things like PostModel to denote a class that can be instantiated for a given post.

**Comment by RaceProUK** [comment]
If no-one objects, I might start putting together a style guide tonight. On the Google Docs thing, obviously :smile:

**Comment by AccaliaDeElementia** [comment]
i wouldn't object. I've been trying to get to it this whole week but.... well i have a *lot* on my plate at work right now. so my energy levels in the evening are..... low.

**Comment by yamikuronue** [comment]
Go for it! Ganbatte!

**Comment by yamikuronue** [comment]
Link is: https://docs.google.com/document/d/1AC53P6Bq_wGIdPCgA6rtJRavoMmgaHqzMgyRNZGNf6o/edit

(captured from chat)

**Comment by yamikuronue** [comment]
Now located at https://github.com/SockDrawer/SockRPG/blob/master/STYLEGUIDE.md
