### ISSUE TITLE
Task: Database structure: Games and Boards

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#37]
Used in features #34 #5 #6  and #7
Create the following entities in the database:

Games
Boards

And create test data that can be inserted into them.

**Comment by RaceProUK** [comment]
Mandatory fields:
- Board
 - ID
 - Name
 - UserID (the creator of the board)
 - GameID (for those boards that have games)
- Game
 - ID

This is enough for a barebones implementation, but I feel we need more than just this smattering of fields. So, what else do we want to store?

Note: For now I'm not worrying about Gamemasters or GameProposals; just sticking with Boards and Games.
