### ISSUE TITLE
Task: Design login flow for OpenID

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#40]
Needed for #3 and #4 

Design and implement, using dummy API data, the login sequence. Hook it up to the login button from #35

**Comment by yamikuronue** [comment]
I took a stab, what do you guys think?

https://gomockingbird.com/projects/tkcjhzo

**Comment by Kaelas17** [comment]
If you look at it from the mockingbird site, the 'screen' is in several different locations- I assume that's just from the mockup, not an actual part of the design, right?

**Comment by yamikuronue** [comment]
Yes, that was unintentional
