### ISSUE TITLE
Task: Update linting to match styleguide

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#42]
This is important to get done :)

**Comment by AccaliaDeElementia** [comment]
Updated with 68b28e492

@RaceProUK can you give the rules i chose a once over and make sure they line up with sanity and the style guide?

**Comment by RaceProUK** [comment]
Aside fromt he tabbing issue we already know about, it all looks OK to me

**Comment by AccaliaDeElementia** [comment]
i'm closing this one as done.

the lint rules will be a living document for a while anyway as we develop and see what false positives (and false negatives) they produce
