### ISSUE TITLE
Feature: Board and Game management

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#5]
## Feature: Board management
As an admin
I want to manage boards
So that I can organize discussions

### Scenario: Create new board
Given I am an admin
And I am logged in
When I create a new board
Then it should be visible to all users

### Scenario: Delete board
Given I am an admin
And I am logged in
And there is at least one board in the system
When I delete a board
Then it should no longer be visible to all users

## Feature: Game management
As an admin
I want to manage games
So that I can control who runs each game

### Scenario: Create new Game
Given I am an admin
And I am logged in
When I create a new Game
Then it should be visible to all users

### Scenario: Assign Gamemaster
Given I am an admin
And a game called FantasyGame1 exists
When I assign user Jane to be the gamemaster of FantasyGame1
Then she should be able to see hidden posts in FantasyGame1
And she should be able to close threads in FantasyGame1
And she should be able to delete FantasyGame1

### Scenario: Delete Game
Given I am an admin or gamemaster
And I am logged in
And there is at least one game in the system
When I delete a game
Then it should no longer be visible to all users

**Comment by TwelveBaud** [comment]
What happens to threads that are on a deleted board? Are they hidden from all users as well? Visible only to participants? Visible only to admins? Are they expunged?

**Comment by yamikuronue** [comment]
That's actually a really good point. See #14

**Comment by yamikuronue** [comment]
To complete this issue:

- Wire together the pieces delivered in tasks #36 #37 and #41 
- Write tests that verify the scenarios above

Feature is complete when tests pass.
