### ISSUE TITLE
What database integration layer do we want to use?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#8]
(Captured from Slack)

accalia [2:33 PM]
ORM or hand code sql/sprocs?

raceprouk [2:33 PM] 
would prefer an ORM

raceprouk [2:33 PM] 
most of our code objects are going to be pretty much 1:1 mappings of DB tables

raceprouk [2:33 PM]
i would think

accalia [2:33 PM] 
do we want a heavyweight framework with lots of available middleware? or something lightweight that won't constrain us to the design decisions of the framework?

accalia [2:34 PM]
what language do we want? I think Node is winning here but we should discuss it

yamikuronue [2:34 PM] 
Is there a good ORM out there that isn't heavyweight and terribly optimized?

accalia [2:34 PM] 
not sure there yami. ¯\_(ツ)_/¯

accalia [2:35 PM]
but we can find out!

accalia [2:35 PM] 
i think performance issues will be something we want to kep an eye on but not a high priority for the first bit.

yamikuronue [2:35 PM] 
I think that should influence the decision more than "do we like ORMs y/n". Let's not get all hyped about a unicorn and then realize it doesn't exist :smile:

accalia [2:35 PM] 
we'll want to keep things performant i mean, but not be super critical about every ms until they add up;

raceprouk [2:35 PM] 
the DB design is more important speed-wise than the ORM

accalia [2:44 PM] 
was planning a simple test harness to create tens of thousands of objects in them and see how they perform

**Comment by yamikuronue** [comment]
yamikuronue [4:02 PM] 
ye gads we talk a lot....  I don't see a summary post, so I'm ont sure I've got it right, but it looks like we were going to try Objection, Sequelize, light-orm, orm

**Comment by AccaliaDeElementia** [comment]
Light-orm has been dropped from consideration, it's an abandoned project.

the other three ORMs are still on the table for testing.

**Comment by AccaliaDeElementia** [comment]
Created #20 to track the implementation effort to trial all three selected ORMs

**Comment by yamikuronue** [comment]
We decided to use Sequelize ORM.
