### ISSUE TITLE
What database backend are we targeting?

### ISSUE THREAD

**Issue by yamikuronue** [SockDrawer/SockRPG#9]
An offshoot of #8 :

raceprouk [4:52 PM] 
so it's just a question of whether i set up tests with one DB engine, or multiple

raceprouk [4:52 PM]
i know we've already decided on an RDBMS

raceprouk [4:52 PM]
but which one?

accalia [4:53 PM] 
i would say use one DB engine for now

accalia [4:53 PM]
we can work on multiple db support later on in the project

raceprouk [4:55 PM] 
if we do it right, supporting multiple DB engines could be as simple as a config switch

raceprouk [4:56 PM]
but i imagine that'd be rather dependent on the ORM we choose

**Comment by AccaliaDeElementia** [comment]
thinking about this i'd love to have postgres and sqlite both officially supported in 1.0.

sqlite will be easier to do devlopment on, and postgres scales well for large sites

**Comment by RaceProUK** [comment]
In which case I'll look into ORM testing on both Postgres and SQLite

**Comment by yamikuronue** [comment]
For now, just those two then :)
